=== qvest-digital/VerA.web/src/main/webapp/WEB-INF/octopus-config/octopus-server.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- Allgemeine Elemente -->

<!--
  Beschreibung der Param Elemente siehe: tc/src/modules/tcModuleConfig.dtd
-->
<!ELEMENT param (value)*>
		<!ATTLIST param
		name CDATA #REQUIRED
		value CDATA #IMPLIED
		type (array|map|scalar) "scalar"
		>

<!ELEMENT value (#PCDATA) >


<!-- Docroot -->
<!ELEMENT tcConfig ( application, loginManager) >


<!-- Section: application 
  Für allgemeine Parameter
-->
<!ELEMENT application ( param )+ >


<!-- Section: loginManager 
  Für die Konfiguration des Loginmanagers
-->
<!ELEMENT loginManager ( param )+ >

=== qvest-digital/VerA.web/core/src/main/webapp/WEB-INF/octopus-config/octopus-server.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file is part of VerA.web by tarent, and covered by the same licence.
-->
<!DOCTYPE tcConfig SYSTEM "octopus-server.dtd">
<!-- Hauptkonfiguration von tarent:config -->
<tcConfig>
	<application>
		<!-- Schaltet die Verwendung der Sessions vom Servlet Container aus.
          true = Dummy Sessions werden für jeden Aufruf erneut angelegt.
          false = Normale Verwendung der HttpSessions
    -->
		<param name="omitSessions" value="false"/>
		<!-- Pfadangaben müssen alle relativ zu '/WEB-INF/' Verzeichniss angegeben werden
         und mit einem '/' enden. -->
		<param name="paths.templateRoot" value="templates/"/>
		<param name="paths.modules" value="modules/"/>
		<!-- Angabe des Stammverzeichnisses der statischen Ressourcen, absolut bezogen auf den Server, also z.B. / -->
		<param name="paths.webRoot" value="/"/>
		<param name="defaultResponseType" value="velocity"/>
		<param name="defaultErrorDescriptionName" value="defaultErrorPage"/>
		<param name="defaultEncoding" value="UTF-8"/>
		<param name="defaultContentType" value="text/html"/>
		<!-- Velocity-Config (Pfade relativ zu modules Verzeichnis) -->
		<param name="velocity.log.system.class" value="de.tarent.octopus.response.TcVelocityResponseLogger"/>
		<param name="velocity.macro.library" value="global.vm"/>
		<param name="velocity.macro.permissions.allow.inline" value="true"/>
		<param name="velocity.macro.permissions.allow.inline.to.replace.global" value="true"/>
		<param name="velocity.macro.permissions.allow.inline.local.scope" value="false"/>
		<param name="velocity.macro.context.localscope" value="false"/>
		<!-- Angabe eines Default Moduls -->
		<param name="defaultModule" value="veraweb"/>
		<!-- Module, die automatsich geladen werden sollen. Space-separiert bei mehreren Modulen
     <param name="preloadModules" value=""/>
     -->
		<!-- Optional JMX connector - only use on Java 1.5 and Tomcat 5.5 -->
		<param name="jmxenabled" value="false"/>
	</application>
	<loginManager>
		<!--
		***************************************************************************************************
		*
		* Die Authorisierungs-Konfiguration kann jetzt direkt in den Modulen in der Sektion <loginManager> der
		* config.xml realisiert werden. Die Einträge hier sind nur noch ein Fallback, für den Fall,
        * dass im Modul selber nichts vorhanden ist.
		*
		***************************************************************************************************
	-->
		<!-- Default Login über xml- User Liste -->
		<param name="loginManagerClass" value="de.tarent.octopus.security.LoginManagerXML"/>
		<param name="userFile" value="user.xml"/>
	</loginManager>
</tcConfig>
