=== qvest-digital/VerA.web/core/src/test/config/tcConfig.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Allgemeine Elemente -->

<!--
  Beschreibung der Param Elemente siehe: tc/src/modules/tcModuleConfig.dtd
-->
<!ELEMENT param (value)*>
		<!ATTLIST param
		name CDATA #REQUIRED
		value CDATA #IMPLIED
		type (array|scalar) "scalar"
		>

<!ELEMENT value (#PCDATA) >

<!-- Docroot -->
<!ELEMENT tcConfig ( application, modules ) >

<!-- Section: application
  FÃ¼r allgemeine Parameter
-->
<!ELEMENT application ( param )+ >

<!-- Section: modules -->
<!--
  Deklaration der Module.
-->
<!ELEMENT modules ( param )+ >

=== qvest-digital/VerA.web/tags/1.2.8/veraweb-war/src/test/config/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
tarent-contact, Plattform-Independent Webservice-Based Contactmanagement
Copyright (C) 2002 tarent GmbH

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

tarent GmbH., hereby disclaims all copyright
interest in the program 'tarent-contact'
(which makes passes at compilers) written
by Michael Klink.
signature of Elmar Geese, 1 June 2002
Elmar Geese, CEO tarent GmbH
-->
<!--
Für LDAP bitte folgendes anpassen:
URL des LDAP-Servers,
den Base-DN des LDAP,
und User/Password für schreibenden Zugriff auf die Kontaktdaten
-->

<!DOCTYPE tcConfig SYSTEM "tcConfig.dtd">

<!-- Hauptkonfiguration von tarent:config -->
<tcConfig>

  <application>    
    <!-- Pfadangaben müssen alle relativ zu '/WEB-INF/' Verzeichniss angegeben werden
         und mit einem '/' enden. -->
    <param name="paths.templateRoot" value="templates/"/>
    <param name="paths.modules" value="modules/"/>

    <param name="defaultResponseType" value="soap"/>
    <param name="defaultErrorDescriptionName" value="defaultErrorPage"/>

    <param name="defaultEncoding" value="ISO-8859-1"/>
    <param name="defaultContentType" value="text/xml"/>

	
  	<param name="auth.type" value="ACCEPT"/>
  	
    <param name="defaultModule" value="testModule"/>
  </application>
</tcConfig>

=== qvest-digital/VerA.web/core/src/test/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Für LDAP bitte folgendes anpassen:
URL des LDAP-Servers,
den Base-DN des LDAP,
und User/Password für schreibenden Zugriff auf die Kontaktdaten
-->
<!DOCTYPE tcConfig SYSTEM "tcConfig.dtd">
<!-- Hauptkonfiguration von tarent:config -->
<tcConfig>
	<application>
		<!-- Pfadangaben müssen alle relativ zu '/WEB-INF/' Verzeichniss angegeben werden
         und mit einem '/' enden. -->
		<param name="paths.templateRoot" value="templates/"/>
		<param name="paths.modules" value="modules/"/>
		<param name="defaultResponseType" value="soap"/>
		<param name="defaultErrorDescriptionName" value="defaultErrorPage"/>
		<param name="defaultEncoding" value="UTF-8"/>
		<param name="defaultContentType" value="text/xml"/>
		<param name="auth.type" value="ACCEPT"/>
		<param name="defaultModule" value="testModule"/>
	</application>
	<modules>
		<param name="onlyNeededToConformWithDtd"/>
	</modules>
</tcConfig>
